# Base image for Python
FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Copy requirements and install dependencies
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# Copy application code
COPY . .

# Command to run the Celery worker
CMD ["celery", "-A", "background_processor.pr_review_celery_job.celery", "worker", "--loglevel=info"]
